architectury {
    common rootProject.ext.enabled_platforms.split(',')
}

loom {
    accessWidenerPath = file("src/main/resources/weatheredwells.accesswidener")
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
            srcDir '../shared/src/main/java'
        }
    }
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    // Architectury API
    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"
}

// Expand pack format variables in pack.mcmeta
processResources {
    inputs.property 'pack_format_min', project.ext.pack_format_min
    inputs.property 'pack_format_max', project.ext.pack_format_max

    filesMatching('pack.mcmeta') {
        expand 'pack_format_min': project.ext.pack_format_min,
               'pack_format_max': project.ext.pack_format_max
    }
}

// Set duplicates strategy for sourcesJar to avoid conflicts
tasks.named('sourcesJar') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
